"""
Django settings for zippo_single project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'files'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '86841k=+^ueqgzi&#^7s#@i+$=u&3fv=0%d!o%_bv!m-e3^6a8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =True#False #True

ALLOWED_HOSTS = ['47.99.151.116']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'device',
    'users',
    'organization',
    'operation',
    'xadmin',
    'crispy_forms',
    'captcha',
    'apps.rbac',
    'macdata',
    'dj_pagination',
]

AUTH_USER_MODEL = "users.UserProfile"

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'rbac.middleware.rbac.RbacMiddle',   # 加入自定义的中间件到最后
    'macdata.views.DisableCSRF',  # macdata 禁止CSRF
    'dj_pagination.middleware.PaginationMiddleware',  #分页
]

ROOT_URLCONF = 'zippo_single.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.i18n',
                'django.core.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'zippo_single.wsgi.application'
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'zippo',
        'USER': 'root',
        'PASSWORD': 'ghqlxy814118',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#login_required URL

LOGIN_URL = '/login/'

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False
'''
# Session setting  
SESSION_COOKIE_AGE = 30 * 60  
SESSION_ENGINE =  'django.contrib.sessions.backends.cache'  

# session_permisson_key  
SESSION_PERMISSION_URL_KEY = "perUrl"  
SESSION_MENU_KEY = "menu"  
MENU_ALL = "menuAll"  
MENU_PERMISSON = "menuPer"  

LOGIN_URL = '/login/'

REGEX_URL = r'^{url}$'  # url作严格匹配

# 配置url权限白名单
SAFE_URL = [
    r'/login/',
    '/admin/.*',
    '/test/',
    '/index/',
    '^/rbac/',
]
'''
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "/home/static/static")
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==========rbac============
PERMISSION_URL_DICT = "permission_url_list"
PERMISSION_MENU_KEY = "permission_menu_list"
APPEND_SLASH=False
WHITE_LIST= [
    '^/login/',
    '^/login/?next=/users/update/pwd/',
    '^/login/?next=/users/info/',
    '^/xadmin/',
    '^/register/',
    '^/forget/',
    '^/users/info/',
    '^/users/update/pwd/',
    '^/user/password/find/',
    '^/users/update_email/',
    '^/image/upload/',
    '^/users/image/upload/',
    '^/logout/',
    '^/captcha/',
    '^/active/(?P<active_code>.*)/',
    '^/reset/(?P<active_code>.*)/',
    '^/modify_pwd/',
    '/org/GetProvinceData/',
    '^/org/GetCityData/',
    '^/org/GetStoreData/',
    #'^/index/2/1/3/4/',
#    '^/upgrade/',
#    '^/data_review/',
    '^/dsky',
    '^/home/',
    '^/org/csv/',
    '^/org/table/',
    '^/device/table/',
    '^/device/tabledetail/',
    '^/device/time/',
    '^/download/',
	'^/org/detailselect/2/0/0/0/?from=2019-01-01&to=2019-01-24&detail=1,'
    #'^/device/resource/',
    #'^/device/software/',
    #'^/device/status/',

]




# 发送邮件的setting设置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = '1623065202@qq.com'
EMAIL_HOST_PASSWORD = 'infznfsfompjdide'
EMAIL_USE_TLS = True
#EMAIL_USE_SSL = True
EMAIL_FROM = '1623065202@qq.com'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER