# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-07 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('roles', models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='用户关联的角色')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='caption',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='title',
            new_name='caption',
        ),
        migrations.AlterField(
            model_name='permission',
            name='menu_gp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm', to='rbac.Permission', verbose_name='组内菜单'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
