# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-08 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20180608_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
    ]
