# Generated by Django 2.0.7 on 2018-07-07 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(default='', max_length=30, verbose_name='mac地址')),
                ('rssi', models.CharField(default='', max_length=10, verbose_name='信号强度')),
                ('range', models.CharField(default='', max_length=10, verbose_name='距离')),
                ('ts', models.CharField(default='', max_length=30, verbose_name='手机连接的Wifi')),
                ('tmc', models.CharField(default='', max_length=30, verbose_name='手机连接Wifi的mac')),
                ('tc', models.CharField(default='', max_length=20, verbose_name='是否与路由器相连')),
                ('ds', models.CharField(default='', max_length=20, verbose_name='手机是否睡眠')),
                ('essid0', models.CharField(default='', max_length=50, verbose_name='连接过wifi0')),
                ('essid1', models.CharField(default='', max_length=50, verbose_name='连接过wifi1')),
                ('essid2', models.CharField(default='', max_length=50, verbose_name='连接过wifi2')),
                ('essid3', models.CharField(default='', max_length=50, verbose_name='连接过wifi3')),
                ('essid4', models.CharField(default='', max_length=50, verbose_name='连接过wifi4')),
                ('essid5', models.CharField(default='', max_length=50, verbose_name='连接过wifi5')),
                ('essid6', models.CharField(default='', max_length=50, verbose_name='连接过wifi6')),
                ('utime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='采集时间')),
            ],
            options={
                'verbose_name_plural': '采集信息',
                'verbose_name': '采集信息',
            },
        ),
        migrations.CreateModel(
            name='MasterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(default='', max_length=30, verbose_name='探测器id')),
                ('rate', models.CharField(default='', max_length=10, verbose_name='发送频率')),
                ('mmac', models.CharField(default='', max_length=30, verbose_name='探测器mac')),
                ('wssid', models.CharField(default='', max_length=30, verbose_name='探测器连接Wifi')),
                ('wmac', models.CharField(default='', max_length=30, verbose_name='探测器连接Wifi')),
                ('lat', models.CharField(default='', max_length=20, verbose_name='纬度')),
                ('lon', models.CharField(default='', max_length=20, verbose_name='经度')),
                ('addr', models.CharField(default='', max_length=50, verbose_name='物理地址')),
                ('utime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='采集时间')),
            ],
            options={
                'verbose_name_plural': '探测器信息',
                'verbose_name': '探测器信息',
            },
        ),
    ]
