# Generated by Django 2.0.7 on 2018-07-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinfo',
            name='mid',
            field=models.CharField(default='', max_length=30, verbose_name='探测器id'),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='mmac',
            field=models.CharField(default='', max_length=30, verbose_name='探测器mac'),
        ),
    ]
