# Generated by Django 2.0.7 on 2018-07-07 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('macdata', '0002_auto_20180707_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_1', models.CharField(default='', max_length=10, verbose_name='距离_1米')),
                ('range_3', models.CharField(default='', max_length=10, verbose_name='距离_3米')),
                ('mid', models.CharField(default='', max_length=30, verbose_name='探测器id')),
                ('mmac', models.CharField(default='', max_length=30, verbose_name='探测器mac')),
                ('utime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='采集时间')),
            ],
            options={
                'verbose_name_plural': '人流量信息',
                'verbose_name': '人流量信息',
            },
        ),
    ]
