# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-19 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('macdata', '0003_macinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacInfo_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi_3m_num', models.IntegerField(default=0, verbose_name='人流量数据(3米)')),
                ('wifi_1m_num', models.IntegerField(default=0, verbose_name='有效客户数(1米)')),
                ('mid', models.CharField(default='', max_length=30, verbose_name='探测器id')),
                ('mmac', models.CharField(default='', max_length=30, verbose_name='探测器mac')),
                ('utime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='采集时间')),
            ],
            options={
                'verbose_name': '人流量信息',
                'verbose_name_plural': '人流量信息',
            },
        ),
        migrations.DeleteModel(
            name='MacInfo',
        ),
    ]
