# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-26 21:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macdata', '0004_auto_20180719_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterinfo',
            name='city',
            field=models.CharField(default='', max_length=20, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='masterinfo',
            name='device_id',
            field=models.CharField(default='', max_length=20, verbose_name='设备编码'),
        ),
        migrations.AddField(
            model_name='masterinfo',
            name='province',
            field=models.CharField(default='', max_length=20, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='masterinfo',
            name='region',
            field=models.CharField(default='', max_length=20, verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='masterinfo',
            name='store',
            field=models.CharField(default='', max_length=20, verbose_name='门店'),
        ),
        migrations.AddField(
            model_name='masterinfo',
            name='time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='时间'),
        ),
    ]
