# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-28 10:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('macdata', '0005_auto_20190326_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterInfo1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(default='', max_length=30, verbose_name='探测器id')),
                ('rate', models.CharField(default='', max_length=10, verbose_name='发送频率')),
                ('mmac', models.CharField(default='', max_length=30, verbose_name='探测器mac')),
                ('wssid', models.CharField(default='', max_length=30, verbose_name='探测器连接Wifi')),
                ('wmac', models.CharField(default='', max_length=30, verbose_name='探测器连接Wifi')),
                ('lat', models.CharField(default='', max_length=20, verbose_name='纬度')),
                ('lon', models.CharField(default='', max_length=20, verbose_name='经度')),
                ('addr', models.CharField(default='', max_length=50, verbose_name='物理地址')),
                ('utime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='采集时间')),
                ('store', models.CharField(default='', max_length=20, verbose_name='门店')),
                ('city', models.CharField(default='', max_length=20, verbose_name='城市')),
                ('province', models.CharField(default='', max_length=20, verbose_name='省份')),
                ('region', models.CharField(default='', max_length=20, verbose_name='区域')),
                ('device_id', models.CharField(default='', max_length=20, verbose_name='设备编码')),
                ('time', models.DateField(default=datetime.datetime.now, verbose_name='时间')),
            ],
            options={
                'verbose_name_plural': '探测器信息',
                'verbose_name': '探测器信息',
            },
        ),
    ]
