# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-02 12:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('macdata', '0006_masterinfo1'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterInfo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(default='', max_length=30, verbose_name='探测器id')),
                ('mmac', models.CharField(default='', max_length=30, verbose_name='探测器mac')),
                ('utime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='采集时间')),
                ('store', models.CharField(default='', max_length=20, verbose_name='门店')),
                ('city', models.CharField(default='', max_length=20, verbose_name='城市')),
                ('province', models.CharField(default='', max_length=20, verbose_name='省份')),
                ('region', models.CharField(default='', max_length=20, verbose_name='区域')),
                ('device_id', models.CharField(default='', max_length=20, verbose_name='设备编码')),
                ('time', models.DateField(default=datetime.datetime.now, verbose_name='时间')),
            ],
            options={
                'verbose_name': '探测器信息',
                'verbose_name_plural': '探测器信息',
            },
        ),
    ]
