# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-04 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='城市')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='描述')),
                ('device_id', models.CharField(default='', max_length=50, verbose_name='rasp设备id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='ProvinceDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='省')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='描述')),
                ('device_id', models.CharField(default='', max_length=50, verbose_name='rasp设备id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
            },
        ),
        migrations.CreateModel(
            name='RegionDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='区域')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='描述')),
                ('device_id', models.CharField(default='', max_length=50, verbose_name='rasp设备id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(default='', max_length=50, verbose_name='门店')),
                ('city', models.CharField(default='', max_length=50, verbose_name='城市')),
                ('province', models.CharField(default='', max_length=50, verbose_name='省份')),
                ('region', models.CharField(default='', max_length=50, verbose_name='区域')),
                ('time', models.DateField(default=datetime.datetime.now, verbose_name='时间')),
                ('classification', models.CharField(default='', max_length=20, verbose_name='分类')),
                ('item', models.CharField(default='', max_length=50, verbose_name='商品型号')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('price', models.FloatField(default=0.0, verbose_name='单价')),
                ('sum', models.FloatField(default=0, verbose_name='总价')),
                ('device_id', models.CharField(default='', max_length=50, verbose_name='rasp设备id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '机具销售',
                'verbose_name_plural': '机具销售',
            },
        ),
        migrations.CreateModel(
            name='SaleProduct_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', max_length=20, verbose_name='区域')),
                ('province', models.CharField(default='', max_length=20, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=20, verbose_name='城市')),
                ('store', models.CharField(default='', max_length=50, verbose_name='门店名')),
                ('time', models.DateField(default=datetime.datetime.now, verbose_name='时间')),
                ('classification', models.CharField(default='', max_length=20, verbose_name='分类')),
                ('item', models.CharField(default='', max_length=50, verbose_name='商品型号')),
                ('quantity_pro', models.IntegerField(default=0, verbose_name='数量')),
                ('price_pro', models.FloatField(default=0.0, verbose_name='单价')),
                ('sum_pro', models.FloatField(default=0, verbose_name='总价')),
                ('quantity_total_pro', models.IntegerField(default=0, verbose_name='累计数量')),
                ('sum_total_pro', models.FloatField(default=0, verbose_name='累计总价')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='录入时间')),
                ('device_id', models.CharField(default='', max_length=50, verbose_name='rasp设备id')),
            ],
            options={
                'verbose_name': '门店数据',
                'verbose_name_plural': '门店数据',
            },
        ),
        migrations.CreateModel(
            name='SaleProduct_day_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(default='', max_length=50, verbose_name='门店名')),
                ('region', models.CharField(default='', max_length=20, verbose_name='区域')),
                ('province', models.CharField(default='', max_length=20, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=20, verbose_name='城市')),
                ('time', models.DateField(default=datetime.datetime.now, verbose_name='时间')),
                ('classification', models.CharField(default='', max_length=20, verbose_name='分类')),
                ('item', models.CharField(default='', max_length=50, verbose_name='商品型号')),
                ('quantity_pro', models.IntegerField(default=0, verbose_name='数量')),
                ('price_pro', models.FloatField(default=0.0, verbose_name='单价')),
                ('sum_pro', models.FloatField(default=0, verbose_name='总价')),
                ('quantity_total_pro', models.IntegerField(default=0, verbose_name='累计数量')),
                ('sum_total_pro', models.FloatField(default=0, verbose_name='累计总价')),
                ('device_id', models.CharField(default='', max_length=50, verbose_name='rasp设备id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '城市数据',
                'verbose_name_plural': '城市数据',
            },
        ),
        migrations.CreateModel(
            name='SaleProduct_day_province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', max_length=20, verbose_name='区域')),
                ('province', models.CharField(default='', max_length=20, verbose_name='省份')),
                ('time', models.DateField(default=datetime.datetime.now, verbose_name='时间')),
                ('classification', models.CharField(default='', max_length=20, verbose_name='分类')),
                ('item', models.CharField(default='', max_length=50, verbose_name='商品型号')),
                ('quantity_pro', models.IntegerField(default=0, verbose_name='数量')),
                ('price_pro', models.FloatField(default=0.0, verbose_name='单价')),
                ('sum_pro', models.FloatField(default=0, verbose_name='总价')),
                ('quantity_total_pro', models.IntegerField(default=0, verbose_name='累计数量')),
                ('sum_total_pro', models.FloatField(default=0, verbose_name='累计总价')),
                ('store', models.CharField(default='', max_length=50, verbose_name='门店名')),
                ('city', models.CharField(default='', max_length=20, verbose_name='城市')),
                ('device_id', models.CharField(default='', max_length=50, verbose_name='rasp设备id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '区域数据',
                'verbose_name_plural': '区域数据',
            },
        ),
        migrations.CreateModel(
            name='SaleProduct_day_region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', max_length=20, verbose_name='区域')),
                ('province', models.CharField(default='', max_length=20, verbose_name='省份')),
                ('time', models.DateField(default=datetime.datetime.now, verbose_name='时间')),
                ('classification', models.CharField(default='', max_length=20, verbose_name='分类')),
                ('item', models.CharField(default='', max_length=50, verbose_name='商品型号')),
                ('quantity_pro', models.IntegerField(default=0, verbose_name='数量')),
                ('price_pro', models.FloatField(default=0.0, verbose_name='单价')),
                ('sum_pro', models.FloatField(default=0, verbose_name='总价')),
                ('quantity_total_pro', models.IntegerField(default=0, verbose_name='累计数量')),
                ('sum_total_pro', models.FloatField(default=0, verbose_name='累计总价')),
                ('store', models.CharField(default='', max_length=50, verbose_name='门店名')),
                ('city', models.CharField(default='', max_length=20, verbose_name='城市')),
                ('device_id', models.CharField(default='', max_length=50, verbose_name='rasp设备id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '区域数据',
                'verbose_name_plural': '区域数据',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='门店名')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='描述')),
                ('device_id', models.CharField(default='', max_length=50, verbose_name='rasp设备id')),
                ('address', models.CharField(default='', max_length=150, verbose_name='机构地址')),
                ('store_id', models.CharField(default='', max_length=10, verbose_name='门店id')),
                ('wifi_id', models.CharField(default='', max_length=50, verbose_name='wifi设备id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('cityname', models.CharField(default='', max_length=30, verbose_name='城市')),
                ('provincename', models.CharField(default='', max_length=30, verbose_name='省份')),
                ('regionname', models.CharField(default='', max_length=30, verbose_name='区域')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='所属城市')),
                ('province', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organization.ProvinceDict', verbose_name='所属省份')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.RegionDict', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '门店',
                'verbose_name_plural': '门店',
            },
        ),
        migrations.CreateModel(
            name='Sum_day_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', max_length=20, verbose_name='区域')),
                ('province', models.CharField(default='', max_length=20, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=20, verbose_name='城市')),
                ('time', models.DateField(default=datetime.datetime.now, verbose_name='时间')),
                ('quantity_pro', models.IntegerField(default=0, verbose_name='数量')),
                ('price_pro', models.FloatField(default=0.0, verbose_name='单价')),
                ('sum_pro', models.FloatField(default=0, verbose_name='总价')),
                ('quantity_total_pro', models.IntegerField(default=0, verbose_name='累计数量')),
                ('sum_total_pro', models.FloatField(default=0, verbose_name='累计总价')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '城市数据',
                'verbose_name_plural': '城市数据',
            },
        ),
        migrations.CreateModel(
            name='Sum_day_province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', max_length=20, verbose_name='区域')),
                ('province', models.CharField(default='', max_length=20, verbose_name='省份')),
                ('time', models.DateField(default=datetime.datetime.now, verbose_name='时间')),
                ('quantity_pro', models.IntegerField(default=0, verbose_name='数量')),
                ('price_pro', models.FloatField(default=0.0, verbose_name='单价')),
                ('sum_pro', models.FloatField(default=0, verbose_name='总价')),
                ('quantity_total_pro', models.IntegerField(default=0, verbose_name='累计数量')),
                ('sum_total_pro', models.FloatField(default=0, verbose_name='累计总价')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '区域数据',
                'verbose_name_plural': '区域数据',
            },
        ),
        migrations.CreateModel(
            name='Sum_day_region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', max_length=20, verbose_name='区域')),
                ('time', models.DateField(default=datetime.datetime.now, verbose_name='时间')),
                ('quantity_pro', models.IntegerField(default=0, verbose_name='数量')),
                ('price_pro', models.FloatField(default=0.0, verbose_name='单价')),
                ('sum_pro', models.FloatField(default=0, verbose_name='总价')),
                ('quantity_total_pro', models.IntegerField(default=0, verbose_name='累计数量')),
                ('sum_total_pro', models.FloatField(default=0, verbose_name='累计总价')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '区域数据',
                'verbose_name_plural': '区域数据',
            },
        ),
        migrations.CreateModel(
            name='Sum_day_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', max_length=20, verbose_name='区域')),
                ('province', models.CharField(default='', max_length=20, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=20, verbose_name='城市')),
                ('store', models.CharField(default='', max_length=50, verbose_name='门店名')),
                ('time', models.DateField(default=datetime.datetime.now, verbose_name='时间')),
                ('quantity_pro', models.IntegerField(default=0, verbose_name='数量')),
                ('price_pro', models.FloatField(default=0.0, verbose_name='单价')),
                ('sum_pro', models.FloatField(default=0, verbose_name='总价')),
                ('quantity_total_pro', models.IntegerField(default=0, verbose_name='累计数量')),
                ('sum_total_pro', models.FloatField(default=0, verbose_name='累计总价')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='录入时间')),
                ('device_id', models.CharField(default='', max_length=50, verbose_name='rasp设备id')),
            ],
            options={
                'verbose_name': '门店数据',
                'verbose_name_plural': '门店数据',
            },
        ),
        migrations.AddField(
            model_name='provincedict',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.RegionDict', verbose_name='所属区域'),
        ),
        migrations.AddField(
            model_name='citydict',
            name='province',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organization.ProvinceDict', verbose_name='所属省份'),
        ),
        migrations.AddField(
            model_name='citydict',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.RegionDict', verbose_name='所属区域'),
        ),
    ]
