# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-12 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='desc',
            field=models.CharField(default='', max_length=200, verbose_name='区域经销商'),
        ),
        migrations.AlterField(
            model_name='provincedict',
            name='desc',
            field=models.CharField(default='', max_length=200, verbose_name='区域经销商'),
        ),
        migrations.AlterField(
            model_name='regiondict',
            name='desc',
            field=models.CharField(default='', max_length=200, verbose_name='区域经销商'),
        ),
        migrations.AlterField(
            model_name='store',
            name='desc',
            field=models.CharField(default='', max_length=200, verbose_name='区域经销商'),
        ),
    ]
