# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-05 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20181212_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct_day',
            name='price_pro',
            field=models.CharField(default='', max_length=50, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day',
            name='quantity_pro',
            field=models.CharField(default='', max_length=50, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day',
            name='quantity_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计数量'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day',
            name='sum_pro',
            field=models.CharField(default='', max_length=50, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day',
            name='sum_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计总价'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day_city',
            name='price_pro',
            field=models.CharField(default='', max_length=50, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day_city',
            name='quantity_pro',
            field=models.CharField(default='', max_length=50, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day_city',
            name='quantity_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计数量'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day_city',
            name='sum_pro',
            field=models.CharField(default='', max_length=50, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day_city',
            name='sum_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计总价'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day_province',
            name='price_pro',
            field=models.CharField(default='', max_length=50, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day_province',
            name='quantity_pro',
            field=models.CharField(default='', max_length=50, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day_province',
            name='quantity_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计数量'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day_province',
            name='sum_pro',
            field=models.CharField(default='', max_length=50, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day_province',
            name='sum_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计总价'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day_region',
            name='price_pro',
            field=models.CharField(default='', max_length=50, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day_region',
            name='quantity_pro',
            field=models.CharField(default='', max_length=50, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day_region',
            name='quantity_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计数量'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day_region',
            name='sum_pro',
            field=models.CharField(default='', max_length=50, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day_region',
            name='sum_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计总价'),
        ),
        migrations.AlterField(
            model_name='sum_day_city',
            name='price_pro',
            field=models.CharField(default='', max_length=50, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='sum_day_city',
            name='quantity_pro',
            field=models.CharField(default='', max_length=50, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='sum_day_city',
            name='quantity_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计数量'),
        ),
        migrations.AlterField(
            model_name='sum_day_city',
            name='sum_pro',
            field=models.CharField(default='', max_length=50, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='sum_day_city',
            name='sum_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计总价'),
        ),
        migrations.AlterField(
            model_name='sum_day_province',
            name='price_pro',
            field=models.CharField(default='', max_length=50, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='sum_day_province',
            name='quantity_pro',
            field=models.CharField(default='', max_length=50, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='sum_day_province',
            name='quantity_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计数量'),
        ),
        migrations.AlterField(
            model_name='sum_day_province',
            name='sum_pro',
            field=models.CharField(default='', max_length=50, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='sum_day_province',
            name='sum_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计总价'),
        ),
        migrations.AlterField(
            model_name='sum_day_region',
            name='price_pro',
            field=models.CharField(default='', max_length=50, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='sum_day_region',
            name='quantity_pro',
            field=models.CharField(default='', max_length=50, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='sum_day_region',
            name='quantity_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计数量'),
        ),
        migrations.AlterField(
            model_name='sum_day_region',
            name='sum_pro',
            field=models.CharField(default='', max_length=50, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='sum_day_region',
            name='sum_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计总价'),
        ),
        migrations.AlterField(
            model_name='sum_day_store',
            name='price_pro',
            field=models.CharField(default='', max_length=50, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='sum_day_store',
            name='quantity_pro',
            field=models.CharField(default='', max_length=50, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='sum_day_store',
            name='quantity_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计数量'),
        ),
        migrations.AlterField(
            model_name='sum_day_store',
            name='sum_pro',
            field=models.CharField(default='', max_length=50, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='sum_day_store',
            name='sum_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计总价'),
        ),
    ]
