# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190205_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct_day',
            name='quantity_total_proj',
            field=models.CharField(default='', max_length=50, verbose_name='火机累计数量'),
        ),
        migrations.AddField(
            model_name='saleproduct_day',
            name='quantity_total_prop',
            field=models.CharField(default='', max_length=50, verbose_name='配件累计数量'),
        ),
        migrations.AddField(
            model_name='saleproduct_day',
            name='sum_total_proj',
            field=models.CharField(default='', max_length=50, verbose_name='火机累计销售额'),
        ),
        migrations.AddField(
            model_name='saleproduct_day',
            name='sum_total_prop',
            field=models.CharField(default='', max_length=50, verbose_name='配件累计销售额'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day',
            name='sum_pro',
            field=models.CharField(default='', max_length=50, verbose_name='销售额'),
        ),
        migrations.AlterField(
            model_name='saleproduct_day',
            name='sum_total_pro',
            field=models.CharField(default='', max_length=50, verbose_name='累计销售额'),
        ),
    ]
