# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-04 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wifiprobedata',
            name='name',
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='interactinfo',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='satisfactiondata',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_day',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_month',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_quarter',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_week',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_year',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='wifiprobedata',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_day',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_month',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_quarter',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_week',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_year',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AlterField(
            model_name='interactinfo',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='互动装置名'),
        ),
    ]
