# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-05 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20180604_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactiondata_day',
            name='time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_month',
            name='time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_quarter',
            name='time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_week',
            name='time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_year',
            name='time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_day',
            name='time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_month',
            name='time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_quarter',
            name='time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_week',
            name='time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_year',
            name='time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='时间'),
        ),
    ]
