# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-08 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20180605_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiprobedata',
            name='mac_list',
            field=models.TextField(default='', verbose_name='有效客户MAC'),
        ),
    ]
