# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-09 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_wifiprobedata_mac_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifiprobedata',
            name='mac_list',
            field=models.TextField(blank=True, null=True, verbose_name='有效'),
        ),
    ]
