# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-09 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20180609_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifiprobedata',
            name='mac_list',
            field=models.TextField(max_length=2000, verbose_name='有效'),
        ),
    ]
