# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-09 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20180609_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wifiprobedata',
            name='mac_list',
        ),
    ]
