# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-25 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_remove_wifiprobedata_mac_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactiondata_day',
            name='store',
            field=models.CharField(default='', max_length=30, verbose_name='门店'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_month',
            name='store',
            field=models.CharField(default='', max_length=30, verbose_name='门店'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_quarter',
            name='store',
            field=models.CharField(default='', max_length=30, verbose_name='门店'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_week',
            name='store',
            field=models.CharField(default='', max_length=30, verbose_name='门店'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_year',
            name='store',
            field=models.CharField(default='', max_length=30, verbose_name='门店'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_day',
            name='store',
            field=models.CharField(default='', max_length=30, verbose_name='门店'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_month',
            name='store',
            field=models.CharField(default='', max_length=30, verbose_name='门店'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_quarter',
            name='store',
            field=models.CharField(default='', max_length=30, verbose_name='门店'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_week',
            name='store',
            field=models.CharField(default='', max_length=30, verbose_name='门店'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_year',
            name='store',
            field=models.CharField(default='', max_length=30, verbose_name='门店'),
        ),
    ]
