# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-31 22:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_auto_20180725_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='offline_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='设备下线时间'),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='online_duration',
            field=models.IntegerField(default=0, verbose_name='设备在线累计时长'),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='online_status',
            field=models.IntegerField(default=0, verbose_name='设备状态'),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='online_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='设备上线时间'),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='时间'),
        ),
    ]
