# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_auto_20180801_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='city',
            field=models.CharField(default='', max_length=30, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='region',
            field=models.CharField(default='', max_length=30, verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='store',
            field=models.CharField(default='', max_length=30, verbose_name='门店'),
        ),
    ]
