# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-10 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0013_auto_20180801_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactiondata_day',
            name='excellent_num_total',
            field=models.IntegerField(default=0, verbose_name='累计满意数'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_day',
            name='good_num_total',
            field=models.IntegerField(default=0, verbose_name='累计一般数'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_day',
            name='unsatisfy_num_total',
            field=models.IntegerField(default=0, verbose_name='累计不满意数'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_month',
            name='excellent_num_total',
            field=models.IntegerField(default=0, verbose_name='累计满意数'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_month',
            name='good_num_total',
            field=models.IntegerField(default=0, verbose_name='累计一般数'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_month',
            name='unsatisfy_num_total',
            field=models.IntegerField(default=0, verbose_name='累计不满意数'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_quarter',
            name='excellent_num_total',
            field=models.IntegerField(default=0, verbose_name='累计满意数'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_quarter',
            name='good_num_total',
            field=models.IntegerField(default=0, verbose_name='累计一般数'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_quarter',
            name='unsatisfy_num_total',
            field=models.IntegerField(default=0, verbose_name='累计不满意数'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_week',
            name='excellent_num_total',
            field=models.IntegerField(default=0, verbose_name='累计满意数'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_week',
            name='good_num_total',
            field=models.IntegerField(default=0, verbose_name='累计一般数'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_week',
            name='unsatisfy_num_total',
            field=models.IntegerField(default=0, verbose_name='累计不满意数'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_year',
            name='excellent_num_total',
            field=models.IntegerField(default=0, verbose_name='累计满意数'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_year',
            name='good_num_total',
            field=models.IntegerField(default=0, verbose_name='累计一般数'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_year',
            name='unsatisfy_num_total',
            field=models.IntegerField(default=0, verbose_name='累计不满意数'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_day',
            name='wifi_1m_num_total',
            field=models.IntegerField(default=0, verbose_name='累计有效客户数(1米)'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_day',
            name='wifi_3m_num_total',
            field=models.IntegerField(default=0, verbose_name='累计人流量数据(3米)'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_month',
            name='wifi_1m_num_total',
            field=models.IntegerField(default=0, verbose_name='累计有效客户数(1米)'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_month',
            name='wifi_3m_num_total',
            field=models.IntegerField(default=0, verbose_name='累计人流量数据(3米)'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_quarter',
            name='wifi_1m_num_total',
            field=models.IntegerField(default=0, verbose_name='累计有效客户数(1米)'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_quarter',
            name='wifi_3m_num_total',
            field=models.IntegerField(default=0, verbose_name='累计人流量数据(3米)'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_week',
            name='wifi_1m_num_total',
            field=models.IntegerField(default=0, verbose_name='累计有效客户数(1米)'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_week',
            name='wifi_3m_num_total',
            field=models.IntegerField(default=0, verbose_name='累计人流量数据(3米)'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_year',
            name='wifi_1m_num_total',
            field=models.IntegerField(default=0, verbose_name='累计有效客户数(1米)'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_year',
            name='wifi_3m_num_total',
            field=models.IntegerField(default=0, verbose_name='累计人流量数据(3米)'),
        ),
    ]
