# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-28 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0016_satisfactiondata_day_city_satisfactiondata_day_region_wifiprobedata_day_city_wifiprobedata_day_regio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satisfactiondata_day_city',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='satisfactiondata_day_city',
            name='name',
        ),
        migrations.RemoveField(
            model_name='satisfactiondata_day_region',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='satisfactiondata_day_region',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wifiprobedata_day_city',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='wifiprobedata_day_city',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wifiprobedata_day_region',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='wifiprobedata_day_region',
            name='name',
        ),
    ]
