# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-16 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0017_auto_20180928_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mqtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='mqtt server ip')),
                ('login_name', models.CharField(default='', max_length=30, verbose_name='登录名')),
                ('password', models.CharField(default='', max_length=30, verbose_name='密码')),
                ('port', models.CharField(default='', max_length=10, verbose_name='端口')),
                ('keepAlive', models.CharField(default='', max_length=10, verbose_name='keepAlive')),
            ],
            options={
                'verbose_name_plural': 'mqtt server',
                'verbose_name': 'mqtt server',
            },
        ),
    ]
