# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-28 00:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0018_mqtt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionData_day_province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.datetime.now, verbose_name='时间')),
                ('excellent_num', models.IntegerField(default=0, verbose_name='满意数')),
                ('good_num', models.IntegerField(default=0, verbose_name='一般数')),
                ('unsatisfy_num', models.IntegerField(default=0, verbose_name='不满意数')),
                ('excellent_num_total', models.IntegerField(default=0, verbose_name='累计满意数')),
                ('good_num_total', models.IntegerField(default=0, verbose_name='累计一般数')),
                ('unsatisfy_num_total', models.IntegerField(default=0, verbose_name='累计不满意数')),
                ('region', models.CharField(default='', max_length=20, verbose_name='区域')),
                ('province', models.CharField(default='', max_length=30, verbose_name='省份')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': '满意度数据(24小时)',
                'verbose_name': '满意度数据(24小时)',
            },
        ),
        migrations.CreateModel(
            name='wifiprobeData_day_province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.datetime.now, verbose_name='时间')),
                ('wifi_3m_num', models.IntegerField(default=0, verbose_name='人流量数据(3米)')),
                ('wifi_1m_num', models.IntegerField(default=0, verbose_name='有效客户数(1米)')),
                ('wifi_3m_num_total', models.IntegerField(default=0, verbose_name='累计人流量数据(3米)')),
                ('wifi_1m_num_total', models.IntegerField(default=0, verbose_name='累计有效客户数(1米)')),
                ('region', models.CharField(default='', max_length=20, verbose_name='区域')),
                ('province', models.CharField(default='', max_length=30, verbose_name='省份')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': '人流量数据(24小时)',
                'verbose_name': '人流量数据(24小时)',
            },
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='province',
            field=models.CharField(default='', max_length=30, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_day',
            name='province',
            field=models.CharField(default='', max_length=30, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_day_city',
            name='province',
            field=models.CharField(default='', max_length=30, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_day',
            name='province',
            field=models.CharField(default='', max_length=30, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_day_city',
            name='province',
            field=models.CharField(default='', max_length=30, verbose_name='省份'),
        ),
    ]
