# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-03 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0019_auto_20181128_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiprobedata_day_city',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_day_province',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='wifiprobedata_day_region',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
    ]
