# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-03 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0021_auto_20181203_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactiondata_day_city',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_day_city',
            name='store',
            field=models.CharField(default='', max_length=30, verbose_name='门店'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_day_province',
            name='city',
            field=models.CharField(default='', max_length=20, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_day_province',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_day_province',
            name='store',
            field=models.CharField(default='', max_length=30, verbose_name='门店'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_day_region',
            name='city',
            field=models.CharField(default='', max_length=20, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_day_region',
            name='device_id',
            field=models.CharField(default='', max_length=30, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_day_region',
            name='province',
            field=models.CharField(default='', max_length=30, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='satisfactiondata_day_region',
            name='store',
            field=models.CharField(default='', max_length=30, verbose_name='门店'),
        ),
    ]
