# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-05 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0022_auto_20181203_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactiondata_day',
            name='excellent_num',
            field=models.CharField(default='', max_length=30, verbose_name='满意数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day',
            name='excellent_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计满意数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day',
            name='good_num',
            field=models.CharField(default='', max_length=30, verbose_name='一般数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day',
            name='good_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计一般数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day',
            name='unsatisfy_num',
            field=models.CharField(default='', max_length=30, verbose_name='不满意数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day',
            name='unsatisfy_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计不满意数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_city',
            name='excellent_num',
            field=models.CharField(default='', max_length=30, verbose_name='满意数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_city',
            name='excellent_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计满意数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_city',
            name='good_num',
            field=models.CharField(default='', max_length=30, verbose_name='一般数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_city',
            name='good_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计一般数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_city',
            name='unsatisfy_num',
            field=models.CharField(default='', max_length=30, verbose_name='不满意数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_city',
            name='unsatisfy_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计不满意数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_province',
            name='excellent_num',
            field=models.CharField(default='', max_length=30, verbose_name='满意数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_province',
            name='excellent_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计满意数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_province',
            name='good_num',
            field=models.CharField(default='', max_length=30, verbose_name='一般数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_province',
            name='good_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计一般数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_province',
            name='unsatisfy_num',
            field=models.CharField(default='', max_length=30, verbose_name='不满意数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_province',
            name='unsatisfy_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计不满意数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_region',
            name='excellent_num',
            field=models.CharField(default='', max_length=30, verbose_name='满意数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_region',
            name='excellent_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计满意数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_region',
            name='good_num',
            field=models.CharField(default='', max_length=30, verbose_name='一般数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_region',
            name='good_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计一般数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_region',
            name='unsatisfy_num',
            field=models.CharField(default='', max_length=30, verbose_name='不满意数'),
        ),
        migrations.AlterField(
            model_name='satisfactiondata_day_region',
            name='unsatisfy_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计不满意数'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day',
            name='wifi_1m_num',
            field=models.CharField(default='', max_length=30, verbose_name='有效客户数(1米)'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day',
            name='wifi_1m_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计有效客户数(1米)'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day',
            name='wifi_3m_num',
            field=models.CharField(default='', max_length=30, verbose_name='人流量数据(3米)'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day',
            name='wifi_3m_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计人流量数据(3米)'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day_city',
            name='wifi_1m_num',
            field=models.CharField(default='', max_length=30, verbose_name='有效客户数(1米)'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day_city',
            name='wifi_1m_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计有效客户数(1米)'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day_city',
            name='wifi_3m_num',
            field=models.CharField(default='', max_length=30, verbose_name='人流量数据(3米)'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day_city',
            name='wifi_3m_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计人流量数据(3米)'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day_province',
            name='wifi_1m_num',
            field=models.CharField(default='', max_length=30, verbose_name='有效客户数(1米)'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day_province',
            name='wifi_1m_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计有效客户数(1米)'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day_province',
            name='wifi_3m_num',
            field=models.CharField(default='', max_length=30, verbose_name='人流量数据(3米)'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day_province',
            name='wifi_3m_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计人流量数据(3米)'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day_region',
            name='wifi_1m_num',
            field=models.CharField(default='', max_length=30, verbose_name='有效客户数(1米)'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day_region',
            name='wifi_1m_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计有效客户数(1米)'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day_region',
            name='wifi_3m_num',
            field=models.CharField(default='', max_length=30, verbose_name='人流量数据(3米)'),
        ),
        migrations.AlterField(
            model_name='wifiprobedata_day_region',
            name='wifi_3m_num_total',
            field=models.CharField(default='', max_length=30, verbose_name='累计人流量数据(3米)'),
        ),
    ]
