# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-02 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0023_auto_20190205_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiprobedata_day',
            name='timer_fenqu',
            field=models.CharField(default='', max_length=20, verbose_name='区间时段'),
        ),
    ]
