# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0024_wifiprobedata_day_timer_fenqu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifiprobedata_day',
            name='timer_fenqu',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
